// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sheason2019/spoved/ent/gitrepo"
	"github.com/sheason2019/spoved/ent/predicate"
	"github.com/sheason2019/spoved/ent/project"
)

// GitRepoQuery is the builder for querying GitRepo entities.
type GitRepoQuery struct {
	config
	ctx          *QueryContext
	order        []OrderFunc
	inters       []Interceptor
	predicates   []predicate.GitRepo
	withProjects *ProjectQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GitRepoQuery builder.
func (grq *GitRepoQuery) Where(ps ...predicate.GitRepo) *GitRepoQuery {
	grq.predicates = append(grq.predicates, ps...)
	return grq
}

// Limit the number of records to be returned by this query.
func (grq *GitRepoQuery) Limit(limit int) *GitRepoQuery {
	grq.ctx.Limit = &limit
	return grq
}

// Offset to start from.
func (grq *GitRepoQuery) Offset(offset int) *GitRepoQuery {
	grq.ctx.Offset = &offset
	return grq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (grq *GitRepoQuery) Unique(unique bool) *GitRepoQuery {
	grq.ctx.Unique = &unique
	return grq
}

// Order specifies how the records should be ordered.
func (grq *GitRepoQuery) Order(o ...OrderFunc) *GitRepoQuery {
	grq.order = append(grq.order, o...)
	return grq
}

// QueryProjects chains the current query on the "projects" edge.
func (grq *GitRepoQuery) QueryProjects() *ProjectQuery {
	query := (&ProjectClient{config: grq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := grq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := grq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gitrepo.Table, gitrepo.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, gitrepo.ProjectsTable, gitrepo.ProjectsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(grq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GitRepo entity from the query.
// Returns a *NotFoundError when no GitRepo was found.
func (grq *GitRepoQuery) First(ctx context.Context) (*GitRepo, error) {
	nodes, err := grq.Limit(1).All(setContextOp(ctx, grq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{gitrepo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (grq *GitRepoQuery) FirstX(ctx context.Context) *GitRepo {
	node, err := grq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GitRepo ID from the query.
// Returns a *NotFoundError when no GitRepo ID was found.
func (grq *GitRepoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = grq.Limit(1).IDs(setContextOp(ctx, grq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{gitrepo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (grq *GitRepoQuery) FirstIDX(ctx context.Context) int {
	id, err := grq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GitRepo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GitRepo entity is found.
// Returns a *NotFoundError when no GitRepo entities are found.
func (grq *GitRepoQuery) Only(ctx context.Context) (*GitRepo, error) {
	nodes, err := grq.Limit(2).All(setContextOp(ctx, grq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{gitrepo.Label}
	default:
		return nil, &NotSingularError{gitrepo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (grq *GitRepoQuery) OnlyX(ctx context.Context) *GitRepo {
	node, err := grq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GitRepo ID in the query.
// Returns a *NotSingularError when more than one GitRepo ID is found.
// Returns a *NotFoundError when no entities are found.
func (grq *GitRepoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = grq.Limit(2).IDs(setContextOp(ctx, grq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{gitrepo.Label}
	default:
		err = &NotSingularError{gitrepo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (grq *GitRepoQuery) OnlyIDX(ctx context.Context) int {
	id, err := grq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GitRepos.
func (grq *GitRepoQuery) All(ctx context.Context) ([]*GitRepo, error) {
	ctx = setContextOp(ctx, grq.ctx, "All")
	if err := grq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GitRepo, *GitRepoQuery]()
	return withInterceptors[[]*GitRepo](ctx, grq, qr, grq.inters)
}

// AllX is like All, but panics if an error occurs.
func (grq *GitRepoQuery) AllX(ctx context.Context) []*GitRepo {
	nodes, err := grq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GitRepo IDs.
func (grq *GitRepoQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, grq.ctx, "IDs")
	if err := grq.Select(gitrepo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (grq *GitRepoQuery) IDsX(ctx context.Context) []int {
	ids, err := grq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (grq *GitRepoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, grq.ctx, "Count")
	if err := grq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, grq, querierCount[*GitRepoQuery](), grq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (grq *GitRepoQuery) CountX(ctx context.Context) int {
	count, err := grq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (grq *GitRepoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, grq.ctx, "Exist")
	switch _, err := grq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (grq *GitRepoQuery) ExistX(ctx context.Context) bool {
	exist, err := grq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GitRepoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (grq *GitRepoQuery) Clone() *GitRepoQuery {
	if grq == nil {
		return nil
	}
	return &GitRepoQuery{
		config:       grq.config,
		ctx:          grq.ctx.Clone(),
		order:        append([]OrderFunc{}, grq.order...),
		inters:       append([]Interceptor{}, grq.inters...),
		predicates:   append([]predicate.GitRepo{}, grq.predicates...),
		withProjects: grq.withProjects.Clone(),
		// clone intermediate query.
		sql:  grq.sql.Clone(),
		path: grq.path,
	}
}

// WithProjects tells the query-builder to eager-load the nodes that are connected to
// the "projects" edge. The optional arguments are used to configure the query builder of the edge.
func (grq *GitRepoQuery) WithProjects(opts ...func(*ProjectQuery)) *GitRepoQuery {
	query := (&ProjectClient{config: grq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	grq.withProjects = query
	return grq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GitURL string `json:"git_url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GitRepo.Query().
//		GroupBy(gitrepo.FieldGitURL).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (grq *GitRepoQuery) GroupBy(field string, fields ...string) *GitRepoGroupBy {
	grq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GitRepoGroupBy{build: grq}
	grbuild.flds = &grq.ctx.Fields
	grbuild.label = gitrepo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GitURL string `json:"git_url,omitempty"`
//	}
//
//	client.GitRepo.Query().
//		Select(gitrepo.FieldGitURL).
//		Scan(ctx, &v)
func (grq *GitRepoQuery) Select(fields ...string) *GitRepoSelect {
	grq.ctx.Fields = append(grq.ctx.Fields, fields...)
	sbuild := &GitRepoSelect{GitRepoQuery: grq}
	sbuild.label = gitrepo.Label
	sbuild.flds, sbuild.scan = &grq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GitRepoSelect configured with the given aggregations.
func (grq *GitRepoQuery) Aggregate(fns ...AggregateFunc) *GitRepoSelect {
	return grq.Select().Aggregate(fns...)
}

func (grq *GitRepoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range grq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, grq); err != nil {
				return err
			}
		}
	}
	for _, f := range grq.ctx.Fields {
		if !gitrepo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if grq.path != nil {
		prev, err := grq.path(ctx)
		if err != nil {
			return err
		}
		grq.sql = prev
	}
	return nil
}

func (grq *GitRepoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GitRepo, error) {
	var (
		nodes       = []*GitRepo{}
		_spec       = grq.querySpec()
		loadedTypes = [1]bool{
			grq.withProjects != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GitRepo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GitRepo{config: grq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, grq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := grq.withProjects; query != nil {
		if err := grq.loadProjects(ctx, query, nodes,
			func(n *GitRepo) { n.Edges.Projects = []*Project{} },
			func(n *GitRepo, e *Project) { n.Edges.Projects = append(n.Edges.Projects, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (grq *GitRepoQuery) loadProjects(ctx context.Context, query *ProjectQuery, nodes []*GitRepo, init func(*GitRepo), assign func(*GitRepo, *Project)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*GitRepo)
	nids := make(map[int]map[*GitRepo]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(gitrepo.ProjectsTable)
		s.Join(joinT).On(s.C(project.FieldID), joinT.C(gitrepo.ProjectsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(gitrepo.ProjectsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(gitrepo.ProjectsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*GitRepo]struct{}{byID[outValue]: {}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "projects" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (grq *GitRepoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := grq.querySpec()
	_spec.Node.Columns = grq.ctx.Fields
	if len(grq.ctx.Fields) > 0 {
		_spec.Unique = grq.ctx.Unique != nil && *grq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, grq.driver, _spec)
}

func (grq *GitRepoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   gitrepo.Table,
			Columns: gitrepo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: gitrepo.FieldID,
			},
		},
		From:   grq.sql,
		Unique: true,
	}
	if unique := grq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := grq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gitrepo.FieldID)
		for i := range fields {
			if fields[i] != gitrepo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := grq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := grq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := grq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := grq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (grq *GitRepoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(grq.driver.Dialect())
	t1 := builder.Table(gitrepo.Table)
	columns := grq.ctx.Fields
	if len(columns) == 0 {
		columns = gitrepo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if grq.sql != nil {
		selector = grq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if grq.ctx.Unique != nil && *grq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range grq.predicates {
		p(selector)
	}
	for _, p := range grq.order {
		p(selector)
	}
	if offset := grq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := grq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GitRepoGroupBy is the group-by builder for GitRepo entities.
type GitRepoGroupBy struct {
	selector
	build *GitRepoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (grgb *GitRepoGroupBy) Aggregate(fns ...AggregateFunc) *GitRepoGroupBy {
	grgb.fns = append(grgb.fns, fns...)
	return grgb
}

// Scan applies the selector query and scans the result into the given value.
func (grgb *GitRepoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, grgb.build.ctx, "GroupBy")
	if err := grgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GitRepoQuery, *GitRepoGroupBy](ctx, grgb.build, grgb, grgb.build.inters, v)
}

func (grgb *GitRepoGroupBy) sqlScan(ctx context.Context, root *GitRepoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(grgb.fns))
	for _, fn := range grgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*grgb.flds)+len(grgb.fns))
		for _, f := range *grgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*grgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := grgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GitRepoSelect is the builder for selecting fields of GitRepo entities.
type GitRepoSelect struct {
	*GitRepoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (grs *GitRepoSelect) Aggregate(fns ...AggregateFunc) *GitRepoSelect {
	grs.fns = append(grs.fns, fns...)
	return grs
}

// Scan applies the selector query and scans the result into the given value.
func (grs *GitRepoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, grs.ctx, "Select")
	if err := grs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GitRepoQuery, *GitRepoSelect](ctx, grs.GitRepoQuery, grs, grs.inters, v)
}

func (grs *GitRepoSelect) sqlScan(ctx context.Context, root *GitRepoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(grs.fns))
	for _, fn := range grs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*grs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := grs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
